### ISSUE TITLE
Support for React 0.14 

### ISSUE THREAD

**Issue by ziahamza** [zilverline/react-tap-event-plugin#24]
React guys released React 0.14 beta. I tried to fork the plugin and try out with React 0.14 beta but I got this error: 

Uncaught TypeError: React.initializeTouchEvents is not a function

**Comment by dmitry** [comment]
@ziahamza it's even not working in 0.13.3 :( https://github.com/zilverline/react-tap-event-plugin/issues/22 Looks like #22 must be fixed first.
